### ISSUE TITLE
Wiki basic structure

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/nsc-events#3]
As a pre-team project manager, I will want to ensure that the the incoming AD430 students have a baseline instructional Wiki. Therefore I will begin planning out edits to current Wiki.

** See BC about push/pull/file naming conventions. **

Story Points: 2-3

**Comment by Seiyaroo** [comment]
Created a basic Wiki structure but will discuss at next meeting. Would like input from team as to what else needs to gain more meat on the Wiki but perhaps for now this is sufficient until the app is more fleshed out and we have images and other pieces together?

**Comment by Seiyaroo** [comment]
For now will close, but we can re-open as a task in the future if needed for further development of Wiki as we grow the project.
