### ISSUE TITLE
Home page: Add NSC Mascot above first upcoming event

### ISSUE THREAD

**Issue by LilithLucifer3x6** [SeattleColleges/nsc-events#50]
- As a developer, I will want to add an image of the school mascot above the first event tile.
- [ ] Add NSC Mascot above first upcoming event on the right. Image can be downloaded from the [media kit].
<img width="1106" alt="Home page (signed in as admin) mascot mock up" src="https://github.com/SeattleColleges/nsc-events/assets/52189566/95c2ea16-870f-4125-8f04-3df81b23bb3e">
<img width="1105" alt="Home page (not signed in) mascot mock up" src="https://github.com/SeattleColleges/nsc-events/assets/52189566/84dc0cb2-71a9-4ddf-853a-3fe2b3f327ab">

**Comment by heosman** [comment]
Issue was picked up by another developer.
